# Generated by Django 4.1.3 on 2022-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
    ]
