# Generated by Django 4.1.3 on 2022-11-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_skills_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='color',
            field=models.CharField(default='blue', max_length=255),
        ),
    ]
