# Generated by Django 4.1.3 on 2022-11-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_skills_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='logo',
        ),
    ]
